// Traductions Allemagne (codes `DE_*`). Libellés + explications en/de/nl/it/es.
//
// Convention identique à `divers.rs` : lignes `[&str; 5]` indexées par langue,
// placeholders nommés substitués côté appelant après lookup. Les termes allemands
// (Lohnsteuer, Grundfreibetrag…) et les références SGB restent intacts.
//
// Outre les 9 lignes de cotisation, ce module fournit des FRAGMENTS traduits
// réinjectés dans les explications via placeholders : libellés de Steuerklasse
// (DE_SK1..6), variantes de Grundfreibetrag (DE_GBF_*), partage KV (DE_KV_PARTAGE_*),
// et mention d'année du Soli (DE_SOLI_ANNEE_*).

pub fn t_libelle(code: &str, lang: &str) -> Option<&'static str> {
    let i = match lang { "en" => 0, "de" => 1, "nl" => 2, "it" => 3, "es" => 4, _ => return None };
    let row: [&str; 5] = match code {
        "DE_KRANKENVERSICHERUNG" => ["KV — Health insurance", "KV — Krankenversicherung", "KV — Ziektekostenverzekering", "KV — Assicurazione malattia", "KV — Seguro de enfermedad"],
        "DE_RENTENVERSICHERUNG" => ["RV — Pension insurance", "RV — Rentenversicherung", "RV — Pensioenverzekering", "RV — Assicurazione pensione", "RV — Seguro de pensión"],
        "DE_ARBEITSLOSENVERSICHERUNG" => ["AV — Unemployment insurance", "AV — Arbeitslosenversicherung", "AV — Werkloosheidsverzekering", "AV — Assicurazione disoccupazione", "AV — Seguro de desempleo"],
        "DE_PFLEGEVERSICHERUNG" => ["PV — Long-term care insurance (with children)", "PV — Pflegeversicherung (mit Kindern)", "PV — Zorgverzekering langdurig (met kinderen)", "PV — Assicurazione dipendenza (con figli)", "PV — Seguro de dependencia (con hijos)"],
        "DE_PV_KINDERLOS" => ["PV — Kinderlosenzuschlag (childless surcharge)", "PV — Kinderlosenzuschlag (Zuschlag für Kinderlose)", "PV — Kinderlosenzuschlag (toeslag kinderlozen)", "PV — Kinderlosenzuschlag (supplemento senza figli)", "PV — Kinderlosenzuschlag (recargo sin hijos)"],
        "DE_UNFALLVERSICHERUNG" => ["UV — Accident insurance (average rate)", "UV — Unfallversicherung (Durchschnittssatz)", "UV — Ongevallenverzekering (gemiddeld tarief)", "UV — Assicurazione infortuni (aliquota media)", "UV — Seguro de accidentes (tipo medio)"],
        "DE_LOHNSTEUER" => ["Lohnsteuer — tax class {sk}", "Lohnsteuer — Steuerklasse {sk}", "Lohnsteuer — belastingklasse {sk}", "Lohnsteuer — classe fiscale {sk}", "Lohnsteuer — clase fiscal {sk}"],
        "DE_SOLI" => ["Solidaritätszuschlag (solidarity surcharge)", "Solidaritätszuschlag", "Solidaritätszuschlag (solidariteitstoeslag)", "Solidaritätszuschlag (sovrattassa di solidarietà)", "Solidaritätszuschlag (recargo de solidaridad)"],
        "DE_KIRCHENSTEUER" => ["Kirchensteuer — church tax ({land} — {tp} %)", "Kirchensteuer ({land} — {tp} %)", "Kirchensteuer — kerkbelasting ({land} — {tp} %)", "Kirchensteuer — imposta di culto ({land} — {tp} %)", "Kirchensteuer — impuesto eclesiástico ({land} — {tp} %)"],
        // ── Libellés de Steuerklasse (fragment {sk}) ──
        "DE_SK1" => ["I — single", "I — ledig", "I — alleenstaand", "I — celibe/nubile", "I — soltero/a"],
        "DE_SK2" => ["II — single parent", "II — Alleinerziehende", "II — alleenstaande ouder", "II — genitore single", "II — progenitor solo"],
        "DE_SK3" => ["III — married (higher earner)", "III — verheiratet (höheres Einkommen)", "III — gehuwd (hoger inkomen)", "III — coniugato/a (reddito alto)", "III — casado/a (renta alta)"],
        "DE_SK4" => ["IV — married (equal earners)", "IV — verheiratet (gleiches Einkommen)", "IV — gehuwd (gelijk inkomen)", "IV — coniugato/a (redditi uguali)", "IV — casado/a (rentas iguales)"],
        "DE_SK5" => ["V — married (lower earner)", "V — verheiratet (niedriges Einkommen)", "V — gehuwd (lager inkomen)", "V — coniugato/a (reddito basso)", "V — casado/a (renta baja)"],
        "DE_SK6" => ["VI — second job", "VI — Zweitjob", "VI — tweede baan", "VI — secondo impiego", "VI — segundo empleo"],
        _ => return None,
    };
    Some(row[i])
}

pub fn t_explication(key: &str, lang: &str) -> Option<&'static str> {
    let i = match lang { "en" => 0, "de" => 1, "nl" => 2, "it" => 3, "es" => 4, _ => return None };
    let row: [&str; 5] = match key {
        "DE_KRANKENVERSICHERUNG" => [
            "The statutory health insurance (GKV) is organised by the GKV-Spitzenverband and governed by SGB V. The general rate (Allgemeiner Beitragssatz) has been 14.6 % since 2015. An additional rate (Zusatzbeitragssatz) is set each year by each fund: {taux_add} % on average for {annee}.\n\n{partage}Base capped at the Beitragsbemessungsgrenze KV: {bbg} €/month in {annee}. Above it, no further KV contribution is due — high earners may opt for private insurance (PKV) if their salary exceeds the Jahresarbeitsentgeltgrenze.",
            "Die gesetzliche Krankenversicherung (GKV) wird vom GKV-Spitzenverband organisiert und durch das SGB V geregelt. Der allgemeine Beitragssatz beträgt seit 2015 14,6 %. Hinzu kommt ein Zusatzbeitragssatz, der jährlich je Kasse festgelegt wird: durchschnittlich {taux_add} % für {annee}.\n\n{partage}Bemessungsgrundlage gedeckelt auf die Beitragsbemessungsgrenze KV: {bbg} €/Monat in {annee}. Darüber hinaus fällt kein weiterer KV-Beitrag an — Besserverdienende können sich privat versichern (PKV), wenn ihr Gehalt die Jahresarbeitsentgeltgrenze übersteigt.",
            "De wettelijke ziektekostenverzekering (GKV) wordt georganiseerd door de GKV-Spitzenverband en geregeld door SGB V. Het algemene tarief (Allgemeiner Beitragssatz) bedraagt sinds 2015 14,6 %. Daar komt een aanvullend tarief (Zusatzbeitragssatz) bij, dat jaarlijks per fonds wordt vastgesteld: gemiddeld {taux_add} % voor {annee}.\n\n{partage}Grondslag begrensd tot de Beitragsbemessungsgrenze KV: {bbg} €/maand in {annee}. Daarboven is geen extra KV-bijdrage verschuldigd — hoge inkomens kunnen voor een particuliere verzekering (PKV) kiezen als hun loon de Jahresarbeitsentgeltgrenze overschrijdt.",
            "L'assicurazione malattia legale (GKV) è organizzata dal GKV-Spitzenverband e disciplinata dal SGB V. L'aliquota generale (Allgemeiner Beitragssatz) è del 14,6 % dal 2015. Si aggiunge un'aliquota integrativa (Zusatzbeitragssatz) fissata ogni anno da ciascuna cassa: in media {taux_add} % per {annee}.\n\n{partage}Base limitata alla Beitragsbemessungsgrenze KV: {bbg} €/mese nel {annee}. Oltre tale soglia non è dovuto alcun contributo KV aggiuntivo — i redditi alti possono optare per un'assicurazione privata (PKV) se la retribuzione supera la Jahresarbeitsentgeltgrenze.",
            "El seguro de enfermedad legal (GKV) está organizado por la GKV-Spitzenverband y regido por el SGB V. El tipo general (Allgemeiner Beitragssatz) es del 14,6 % desde 2015. Se añade un tipo adicional (Zusatzbeitragssatz) fijado cada año por cada caja: {taux_add} % de media para {annee}.\n\n{partage}Base limitada a la Beitragsbemessungsgrenze KV: {bbg} €/mes en {annee}. Por encima no se debe ninguna cotización KV adicional — las rentas altas pueden optar por un seguro privado (PKV) si su salario supera la Jahresarbeitsentgeltgrenze.",
        ],
        "DE_RENTENVERSICHERUNG" => [
            "The statutory pension insurance (GRV) is managed by the Deutsche Rentenversicherung (DRV). It is pay-as-you-go (Umlageverfahren): current contributions fund current pensions. The rate is {taux} % ({ts} % employee + {tp} % employer).\n\nBase capped at the Beitragsbemessungsgrenze RV: {bbg} €/month in {annee}. Since 01/01/2025 this limit is unified East/West (previously the Neue Länder had a separate, lower ceiling).\n\nThe pension is computed in Entgeltpunkte (earnings points): each year, 1 point = the national average wage. The value of a point (Rentenwert) is revalued annually.",
            "Die gesetzliche Rentenversicherung (GRV) wird von der Deutschen Rentenversicherung (DRV) verwaltet. Sie funktioniert im Umlageverfahren: Die aktuellen Beiträge finanzieren die laufenden Renten. Der Satz beträgt {taux} % ({ts} % Arbeitnehmer + {tp} % Arbeitgeber).\n\nBemessungsgrundlage gedeckelt auf die Beitragsbemessungsgrenze RV: {bbg} €/Monat in {annee}. Seit dem 01.01.2025 ist diese Grenze Ost/West vereinheitlicht (zuvor hatten die Neuen Länder eine eigene, niedrigere Grenze).\n\nDie Rente wird in Entgeltpunkten berechnet: Jedes Jahr entspricht 1 Punkt dem nationalen Durchschnittslohn. Der Wert eines Punktes (Rentenwert) wird jährlich angepasst.",
            "De wettelijke pensioenverzekering (GRV) wordt beheerd door de Deutsche Rentenversicherung (DRV). Ze werkt via omslag (Umlageverfahren): de huidige bijdragen financieren de lopende pensioenen. Het tarief bedraagt {taux} % ({ts} % werknemer + {tp} % werkgever).\n\nGrondslag begrensd tot de Beitragsbemessungsgrenze RV: {bbg} €/maand in {annee}. Sinds 01-01-2025 is deze grens Oost/West gelijkgetrokken (voorheen hadden de Neue Länder een aparte, lagere grens).\n\nHet pensioen wordt berekend in Entgeltpunkte (inkomenspunten): elk jaar staat 1 punt gelijk aan het nationale gemiddelde loon. De waarde van een punt (Rentenwert) wordt jaarlijks herzien.",
            "L'assicurazione pensione legale (GRV) è gestita dalla Deutsche Rentenversicherung (DRV). Funziona a ripartizione (Umlageverfahren): i contributi attuali finanziano le pensioni in corso. L'aliquota è del {taux} % ({ts} % dipendente + {tp} % datore di lavoro).\n\nBase limitata alla Beitragsbemessungsgrenze RV: {bbg} €/mese nel {annee}. Dal 01/01/2025 questo limite è unificato Est/Ovest (in precedenza i Neue Länder avevano un massimale distinto e più basso).\n\nLa pensione è calcolata in Entgeltpunkte (punti di reddito): ogni anno, 1 punto = salario medio nazionale. Il valore di un punto (Rentenwert) è rivalutato annualmente.",
            "El seguro de pensión legal (GRV) está gestionado por la Deutsche Rentenversicherung (DRV). Funciona por reparto (Umlageverfahren): las cotizaciones actuales financian las pensiones en curso. El tipo es del {taux} % ({ts} % trabajador + {tp} % empleador).\n\nBase limitada a la Beitragsbemessungsgrenze RV: {bbg} €/mes en {annee}. Desde el 01/01/2025 este límite está unificado Este/Oeste (antes, los Neue Länder tenían un tope distinto y más bajo).\n\nLa pensión se calcula en Entgeltpunkte (puntos de ingreso): cada año, 1 punto = salario medio nacional. El valor de un punto (Rentenwert) se revaloriza anualmente.",
        ],
        "DE_ARBEITSLOSENVERSICHERUNG" => [
            "Unemployment insurance (SGB III) is managed by the Bundesagentur für Arbeit (BA). Rate {annee}: {taux} % ({ts} % each). Rate history: 3.0 % (2015-2018) → 2.6 % (2019, Qualifizierungschancengesetz) → 2.4 % (2020-2022, temporary cut) → 2.6 % (2023+). Same capped base as the RV: {bbg} €/month in {annee}.",
            "Die Arbeitslosenversicherung (SGB III) wird von der Bundesagentur für Arbeit (BA) verwaltet. Satz {annee}: {taux} % ({ts} % je). Satzverlauf: 3,0 % (2015-2018) → 2,6 % (2019, Qualifizierungschancengesetz) → 2,4 % (2020-2022, vorübergehende Senkung) → 2,6 % (2023+). Gleiche gedeckelte Bemessungsgrundlage wie die RV: {bbg} €/Monat in {annee}.",
            "De werkloosheidsverzekering (SGB III) wordt beheerd door de Bundesagentur für Arbeit (BA). Tarief {annee}: {taux} % ({ts} % elk). Tariefverloop: 3,0 % (2015-2018) → 2,6 % (2019, Qualifizierungschancengesetz) → 2,4 % (2020-2022, tijdelijke verlaging) → 2,6 % (2023+). Zelfde begrensde grondslag als de RV: {bbg} €/maand in {annee}.",
            "L'assicurazione disoccupazione (SGB III) è gestita dalla Bundesagentur für Arbeit (BA). Aliquota {annee}: {taux} % ({ts} % ciascuno). Storico aliquote: 3,0 % (2015-2018) → 2,6 % (2019, Qualifizierungschancengesetz) → 2,4 % (2020-2022, riduzione temporanea) → 2,6 % (2023+). Stessa base limitata della RV: {bbg} €/mese nel {annee}.",
            "El seguro de desempleo (SGB III) está gestionado por la Bundesagentur für Arbeit (BA). Tipo {annee}: {taux} % ({ts} % cada uno). Histórico de tipos: 3,0 % (2015-2018) → 2,6 % (2019, Qualifizierungschancengesetz) → 2,4 % (2020-2022, reducción temporal) → 2,6 % (2023+). Misma base limitada que la RV: {bbg} €/mes en {annee}.",
        ],
        "DE_PFLEGEVERSICHERUNG" => [
            "Long-term care insurance (Pflegeversicherung, SGB XI) funds care for dependent persons (Pflegegrade 1 to 5). Rate {annee}: {taux} % ({ts} % each). Historical progression: 2.35 % (2015-2016) → 2.55 % (2017-2018) → 3.05 % (2019-06/2023) → 3.40 % (07/2023, PUEG reform) → 3.60 % (2025+). Base capped at the Beitragsbemessungsgrenze KV: {bbg} €/month. Childless persons pay a surcharge (Kinderlosenzuschlag) — see dedicated line.",
            "Die Pflegeversicherung (SGB XI) finanziert die Pflege pflegebedürftiger Personen (Pflegegrade 1 bis 5). Satz {annee}: {taux} % ({ts} % je). Historische Entwicklung: 2,35 % (2015-2016) → 2,55 % (2017-2018) → 3,05 % (2019-06/2023) → 3,40 % (07/2023, PUEG-Reform) → 3,60 % (2025+). Bemessungsgrundlage gedeckelt auf die Beitragsbemessungsgrenze KV: {bbg} €/Monat. Kinderlose zahlen einen Zuschlag (Kinderlosenzuschlag) — siehe eigene Zeile.",
            "De langdurigezorgverzekering (Pflegeversicherung, SGB XI) financiert de zorg voor zorgbehoevenden (Pflegegrade 1 tot 5). Tarief {annee}: {taux} % ({ts} % elk). Historisch verloop: 2,35 % (2015-2016) → 2,55 % (2017-2018) → 3,05 % (2019-06/2023) → 3,40 % (07/2023, PUEG-hervorming) → 3,60 % (2025+). Grondslag begrensd tot de Beitragsbemessungsgrenze KV: {bbg} €/maand. Kinderlozen betalen een toeslag (Kinderlosenzuschlag) — zie aparte regel.",
            "L'assicurazione dipendenza (Pflegeversicherung, SGB XI) finanzia l'assistenza alle persone non autosufficienti (Pflegegrade da 1 a 5). Aliquota {annee}: {taux} % ({ts} % ciascuno). Evoluzione storica: 2,35 % (2015-2016) → 2,55 % (2017-2018) → 3,05 % (2019-06/2023) → 3,40 % (07/2023, riforma PUEG) → 3,60 % (2025+). Base limitata alla Beitragsbemessungsgrenze KV: {bbg} €/mese. Le persone senza figli pagano un supplemento (Kinderlosenzuschlag) — vedi riga dedicata.",
            "El seguro de dependencia (Pflegeversicherung, SGB XI) financia los cuidados a las personas dependientes (Pflegegrade 1 a 5). Tipo {annee}: {taux} % ({ts} % cada uno). Evolución histórica: 2,35 % (2015-2016) → 2,55 % (2017-2018) → 3,05 % (2019-06/2023) → 3,40 % (07/2023, reforma PUEG) → 3,60 % (2025+). Base limitada a la Beitragsbemessungsgrenze KV: {bbg} €/mes. Las personas sin hijos pagan un recargo (Kinderlosenzuschlag) — véase línea dedicada.",
        ],
        "DE_PV_KINDERLOS" => [
            "Childless persons over 23 pay an employee surcharge (Kinderlosenzuschlag) under the Pflegeversicherung. Current rate: {ts} % employee only (employer exempt). History: +0.25 % (2005-2021) → +0.35 % (2022-06/2023) → +0.60 % (07/2023+). The PUEG reform of July 2023 also introduced graduated reductions for large families (2 to 5 children), not simulated here.",
            "Kinderlose über 23 Jahre zahlen einen Arbeitnehmerzuschlag (Kinderlosenzuschlag) zur Pflegeversicherung. Aktueller Satz: {ts} % nur Arbeitnehmer (Arbeitgeber befreit). Historie: +0,25 % (2005-2021) → +0,35 % (2022-06/2023) → +0,60 % (07/2023+). Die PUEG-Reform vom Juli 2023 führte außerdem gestaffelte Ermäßigungen für kinderreiche Familien (2 bis 5 Kinder) ein, hier nicht simuliert.",
            "Kinderlozen ouder dan 23 betalen een werknemerstoeslag (Kinderlosenzuschlag) voor de Pflegeversicherung. Huidig tarief: {ts} % alleen werknemer (werkgever vrijgesteld). Historie: +0,25 % (2005-2021) → +0,35 % (2022-06/2023) → +0,60 % (07/2023+). De PUEG-hervorming van juli 2023 voerde ook gestaffelde verlagingen in voor grote gezinnen (2 tot 5 kinderen), hier niet gesimuleerd.",
            "Le persone senza figli con più di 23 anni pagano un supplemento a carico del dipendente (Kinderlosenzuschlag) per la Pflegeversicherung. Aliquota attuale: {ts} % solo dipendente (datore di lavoro esentato). Storico: +0,25 % (2005-2021) → +0,35 % (2022-06/2023) → +0,60 % (07/2023+). La riforma PUEG del luglio 2023 ha inoltre introdotto riduzioni graduali per le famiglie numerose (da 2 a 5 figli), qui non simulate.",
            "Las personas sin hijos mayores de 23 años pagan un recargo a cargo del trabajador (Kinderlosenzuschlag) por la Pflegeversicherung. Tipo actual: {ts} % solo trabajador (empleador exento). Histórico: +0,25 % (2005-2021) → +0,35 % (2022-06/2023) → +0,60 % (07/2023+). La reforma PUEG de julio de 2023 introdujo además reducciones graduales para familias numerosas (2 a 5 hijos), no simuladas aquí.",
        ],
        "DE_UNFALLVERSICHERUNG" => [
            "Occupational accident and disease insurance (SGB VII) is borne exclusively by the employer. It is managed by sector-specific Berufsgenossenschaften (BG), each setting its own rate according to the company's risk class.\n\nRange: ~0.5 % (services/administration) to ~3.5 % (construction, heavy industry). The rate shown here is the indicative DGUV national average (~1.3 %). The base is the full gross salary, with no ceiling (unlike the other contributions).",
            "Die Versicherung gegen Arbeitsunfälle und Berufskrankheiten (SGB VII) trägt ausschließlich der Arbeitgeber. Sie wird von branchenspezifischen Berufsgenossenschaften (BG) verwaltet, die jeweils ihren eigenen Satz nach der Gefahrklasse des Unternehmens festlegen.\n\nSpanne: ~0,5 % (Dienstleistung/Verwaltung) bis ~3,5 % (Bau, Schwerindustrie). Der hier angezeigte Satz ist der indikative DGUV-Bundesdurchschnitt (~1,3 %). Bemessungsgrundlage ist das Bruttogehalt ohne Obergrenze (im Gegensatz zu den anderen Beiträgen).",
            "De verzekering tegen arbeidsongevallen en beroepsziekten (SGB VII) komt uitsluitend voor rekening van de werkgever. Ze wordt beheerd door sectorale Berufsgenossenschaften (BG), die elk hun eigen tarief vaststellen volgens de risicoklasse van de onderneming.\n\nMarge: ~0,5 % (diensten/administratie) tot ~3,5 % (bouw, zware industrie). Het hier getoonde tarief is het indicatieve landelijke DGUV-gemiddelde (~1,3 %). De grondslag is het brutoloon zonder plafond (in tegenstelling tot de andere bijdragen).",
            "L'assicurazione contro gli infortuni sul lavoro e le malattie professionali (SGB VII) è esclusivamente a carico del datore di lavoro. È gestita da Berufsgenossenschaften (BG) settoriali, ciascuna delle quali fissa la propria aliquota in base alla classe di rischio dell'impresa.\n\nIntervallo: ~0,5 % (servizi/amministrazione) a ~3,5 % (edilizia, industria pesante). L'aliquota qui mostrata è la media nazionale indicativa DGUV (~1,3 %). La base è la retribuzione lorda senza massimale (a differenza degli altri contributi).",
            "El seguro de accidentes de trabajo y enfermedades profesionales (SGB VII) corre exclusivamente a cargo del empleador. Está gestionado por Berufsgenossenschaften (BG) sectoriales, cada una de las cuales fija su propio tipo según la clase de riesgo de la empresa.\n\nHorquilla: ~0,5 % (servicios/administración) a ~3,5 % (construcción, industria pesada). El tipo mostrado aquí es la media nacional indicativa DGUV (~1,3 %). La base es el salario bruto sin tope (a diferencia de las demás cotizaciones).",
        ],
        "DE_LOHNSTEUER" => [
            "The Lohnsteuer is the German wage tax, withheld at source by the employer (EStG §38). It is computed on the annualised income ({revenu_an} €/yr) under the progressive scale EStG §32a, then divided by 12 for the monthly payslip.\n\nSteuerklasse {skn} ({skl}): {gbf_info}.\n\nGrundfreibetrag {annee}: {gbf} €/yr. {annee} scale: 0 % up to the Grundfreibetrag → progression 14 %-42 % → top marginal rate 42 % (Spitzensteuersatz) → 45 % above 277,825 €/yr.\n\nComputed annual Lohnsteuer: {lst_an} € → monthly: {lst_m} €. Note: the effective rate shown is indicative (monthly LSt / monthly gross).",
            "Die Lohnsteuer ist die deutsche Steuer auf Löhne, vom Arbeitgeber an der Quelle einbehalten (EStG §38). Sie wird auf das auf das Jahr hochgerechnete Einkommen ({revenu_an} €/Jahr) nach dem progressiven Tarif EStG §32a berechnet und dann für den Monatslohn durch 12 geteilt.\n\nSteuerklasse {skn} ({skl}): {gbf_info}.\n\nGrundfreibetrag {annee}: {gbf} €/Jahr. Tarif {annee}: 0 % bis zum Grundfreibetrag → Progression 14 %-42 % → Spitzensteuersatz 42 % → 45 % über 277 825 €/Jahr.\n\nBerechnete Jahres-Lohnsteuer: {lst_an} € → monatlich: {lst_m} €. Hinweis: Der angezeigte effektive Satz ist indikativ (monatl. LSt / monatl. Brutto).",
            "De Lohnsteuer is de Duitse loonbelasting, aan de bron ingehouden door de werkgever (EStG §38). Ze wordt berekend op het naar jaarbasis omgerekende inkomen ({revenu_an} €/jr) volgens de progressieve schaal EStG §32a, en daarna door 12 gedeeld voor de maandstrook.\n\nSteuerklasse {skn} ({skl}): {gbf_info}.\n\nGrundfreibetrag {annee}: {gbf} €/jr. Schaal {annee}: 0 % tot de Grundfreibetrag → progressie 14 %-42 % → toptarief 42 % (Spitzensteuersatz) → 45 % boven 277.825 €/jr.\n\nBerekende jaarlijkse Lohnsteuer: {lst_an} € → maandelijks: {lst_m} €. Opmerking: het getoonde effectieve tarief is indicatief (maandelijkse LSt / maandelijks bruto).",
            "La Lohnsteuer è l'imposta tedesca sui salari, trattenuta alla fonte dal datore di lavoro (EStG §38). È calcolata sul reddito annualizzato ({revenu_an} €/anno) secondo la scala progressiva EStG §32a, poi divisa per 12 per il cedolino mensile.\n\nSteuerklasse {skn} ({skl}): {gbf_info}.\n\nGrundfreibetrag {annee}: {gbf} €/anno. Scala {annee}: 0 % fino al Grundfreibetrag → progressione 14 %-42 % → aliquota marginale massima 42 % (Spitzensteuersatz) → 45 % oltre 277 825 €/anno.\n\nLohnsteuer annua calcolata: {lst_an} € → mensile: {lst_m} €. Nota: l'aliquota effettiva mostrata è indicativa (LSt mensile / lordo mensile).",
            "La Lohnsteuer es el impuesto alemán sobre los salarios, retenido en origen por el empleador (EStG §38). Se calcula sobre la renta anualizada ({revenu_an} €/año) según la escala progresiva EStG §32a, y luego se divide entre 12 para la nómina mensual.\n\nSteuerklasse {skn} ({skl}): {gbf_info}.\n\nGrundfreibetrag {annee}: {gbf} €/año. Escala {annee}: 0 % hasta el Grundfreibetrag → progresión 14 %-42 % → tipo marginal máximo 42 % (Spitzensteuersatz) → 45 % por encima de 277 825 €/año.\n\nLohnsteuer anual calculada: {lst_an} € → mensual: {lst_m} €. Nota: el tipo efectivo mostrado es indicativo (LSt mensual / bruto mensual).",
        ],
        "DE_SOLI" => [
            "The Solidaritätszuschlag (\"Soli\") is a 5.5 % surcharge on the Lohnsteuer, introduced in 1991 to finance German reunification (SolZG). Since 01/01/2021 it is abolished for ~90 % of taxpayers: exempt if annual Lohnsteuer ≤ {seuil} €. Transition zone up to {seuil_haut} € of annual Lohnsteuer: progressive rate 11.9 %. Above: full rate 5.5 %. {annee_info}",
            "Der Solidaritätszuschlag (\"Soli\") ist ein Zuschlag von 5,5 % auf die Lohnsteuer, 1991 zur Finanzierung der deutschen Wiedervereinigung eingeführt (SolZG). Seit dem 01.01.2021 entfällt er für ~90 % der Steuerzahler: befreit, wenn die jährliche Lohnsteuer ≤ {seuil} €. Übergangszone bis {seuil_haut} € jährliche Lohnsteuer: progressiver Satz 11,9 %. Darüber: voller Satz 5,5 %. {annee_info}",
            "De Solidaritätszuschlag (\"Soli\") is een toeslag van 5,5 % op de Lohnsteuer, in 1991 ingevoerd ter financiering van de Duitse hereniging (SolZG). Sinds 01-01-2021 vervalt hij voor ~90 % van de belastingplichtigen: vrijgesteld als de jaarlijkse Lohnsteuer ≤ {seuil} €. Overgangszone tot {seuil_haut} € jaarlijkse Lohnsteuer: progressief tarief 11,9 %. Daarboven: vol tarief 5,5 %. {annee_info}",
            "Il Solidaritätszuschlag (\"Soli\") è una sovrattassa del 5,5 % sulla Lohnsteuer, istituita nel 1991 per finanziare la riunificazione tedesca (SolZG). Dal 01/01/2021 è soppressa per ~90 % dei contribuenti: esente se la Lohnsteuer annua ≤ {seuil} €. Zona di transizione fino a {seuil_haut} € di Lohnsteuer annua: aliquota progressiva 11,9 %. Oltre: aliquota piena 5,5 %. {annee_info}",
            "El Solidaritätszuschlag (\"Soli\") es un recargo del 5,5 % sobre la Lohnsteuer, instaurado en 1991 para financiar la reunificación alemana (SolZG). Desde el 01/01/2021 se suprime para ~90 % de los contribuyentes: exento si la Lohnsteuer anual ≤ {seuil} €. Zona de transición hasta {seuil_haut} € de Lohnsteuer anual: tipo progresivo 11,9 %. Por encima: tipo pleno 5,5 %. {annee_info}",
        ],
        "DE_KIRCHENSTEUER" => [
            "The church tax (Kirchensteuer) is withheld by the employer on the Lohnsteuer for the major faiths (Catholic, Protestant, Jewish). It is mandatory if the employee is registered as a member with the tax authority (Finanzamt).\n\nRate in {land}: {taux_pct} % of the Lohnsteuer. Bayern (BY) and Baden-Württemberg (BW) apply 8 %, the other 14 Länder apply 9 %.\n\nThe employee can opt out (Kirchenaustritt) at the civil registry — the Kirchensteuer then disappears from the payslip.",
            "Die Kirchensteuer wird vom Arbeitgeber auf die Lohnsteuer zugunsten der großen Konfessionen (katholisch, evangelisch, jüdisch) einbehalten. Sie ist verpflichtend, wenn der Arbeitnehmer beim Finanzamt als Mitglied registriert ist.\n\nSatz in {land}: {taux_pct} % der Lohnsteuer. Bayern (BY) und Baden-Württemberg (BW) wenden 8 % an, die übrigen 14 Länder 9 %.\n\nDer Arbeitnehmer kann austreten (Kirchenaustritt) beim Standesamt — die Kirchensteuer entfällt dann auf dem Lohnzettel.",
            "De kerkbelasting (Kirchensteuer) wordt door de werkgever ingehouden op de Lohnsteuer ten gunste van de grote geloofsrichtingen (katholiek, protestants, joods). Ze is verplicht als de werknemer als lid is geregistreerd bij de belastingdienst (Finanzamt).\n\nTarief in {land}: {taux_pct} % van de Lohnsteuer. Bayern (BY) en Baden-Württemberg (BW) passen 8 % toe, de andere 14 Länder 9 %.\n\nDe werknemer kan uittreden (Kirchenaustritt) bij de burgerlijke stand — de Kirchensteuer verdwijnt dan van de loonstrook.",
            "L'imposta di culto (Kirchensteuer) è trattenuta dal datore di lavoro sulla Lohnsteuer a favore delle grandi confessioni (cattolica, protestante, ebraica). È obbligatoria se il dipendente è registrato come membro presso l'amministrazione fiscale (Finanzamt).\n\nAliquota in {land}: {taux_pct} % della Lohnsteuer. Bayern (BY) e Baden-Württemberg (BW) applicano l'8 %, gli altri 14 Länder il 9 %.\n\nIl dipendente può recedere (Kirchenaustritt) presso l'anagrafe — la Kirchensteuer scompare allora dal cedolino.",
            "El impuesto eclesiástico (Kirchensteuer) lo retiene el empleador sobre la Lohnsteuer en favor de las grandes confesiones (católica, protestante, judía). Es obligatorio si el trabajador está registrado como miembro ante la administración fiscal (Finanzamt).\n\nTipo en {land}: {taux_pct} % de la Lohnsteuer. Bayern (BY) y Baden-Württemberg (BW) aplican el 8 %, los otros 14 Länder el 9 %.\n\nEl trabajador puede darse de baja (Kirchenaustritt) en el registro civil — la Kirchensteuer desaparece entonces de la nómina.",
        ],
        // ── Fragments réinjectés (partage KV, gbf_info, annee_info Soli) ──
        "DE_KV_PARTAGE_POST" => [
            "Since the GKV-VEG reform of 01/01/2019, the Zusatzbeitrag is shared equally between employee and employer. Before 2019 it was borne entirely by the employee. ",
            "Seit der GKV-VEG-Reform vom 01.01.2019 wird der Zusatzbeitrag paritätisch zwischen Arbeitnehmer und Arbeitgeber geteilt. Vor 2019 trug ihn der Arbeitnehmer allein. ",
            "Sinds de GKV-VEG-hervorming van 01-01-2019 wordt de Zusatzbeitrag gelijk verdeeld tussen werknemer en werkgever. Vóór 2019 kwam hij volledig voor rekening van de werknemer. ",
            "Dalla riforma GKV-VEG del 01/01/2019, il Zusatzbeitrag è ripartito in parti uguali tra dipendente e datore di lavoro. Prima del 2019 era interamente a carico del dipendente. ",
            "Desde la reforma GKV-VEG del 01/01/2019, el Zusatzbeitrag se reparte por igual entre trabajador y empleador. Antes de 2019 corría íntegramente a cargo del trabajador. ",
        ],
        "DE_KV_PARTAGE_PRE" => [
            "Before the GKV-VEG reform (2019), the Zusatzbeitrag was borne entirely by the employee — hence the rate asymmetry here. ",
            "Vor der GKV-VEG-Reform (2019) trug der Arbeitnehmer den Zusatzbeitrag allein — daher die Asymmetrie der Sätze hier. ",
            "Vóór de GKV-VEG-hervorming (2019) kwam de Zusatzbeitrag volledig voor rekening van de werknemer — vandaar de asymmetrie van de tarieven hier. ",
            "Prima della riforma GKV-VEG (2019), il Zusatzbeitrag era interamente a carico del dipendente — da cui l'asimmetria delle aliquote qui. ",
            "Antes de la reforma GKV-VEG (2019), el Zusatzbeitrag corría íntegramente a cargo del trabajador — de ahí la asimetría de los tipos aquí. ",
        ],
        "DE_GBF_STD" => [
            "Grundfreibetrag ({gbf} €/yr) applied", "Grundfreibetrag ({gbf} €/Jahr) angewandt", "Grundfreibetrag ({gbf} €/jr) toegepast", "Grundfreibetrag ({gbf} €/anno) applicato", "Grundfreibetrag ({gbf} €/año) aplicado",
        ],
        "DE_GBF_SK2" => [
            "Grundfreibetrag + Entlastungsbetrag for single parents ({ent} €/yr)", "Grundfreibetrag + Entlastungsbetrag für Alleinerziehende ({ent} €/Jahr)", "Grundfreibetrag + Entlastungsbetrag voor alleenstaande ouders ({ent} €/jr)", "Grundfreibetrag + Entlastungsbetrag per genitori single ({ent} €/anno)", "Grundfreibetrag + Entlastungsbetrag para progenitores solos ({ent} €/año)",
        ],
        "DE_GBF_SK3" => [
            "Grundfreibetrag doubled ({gbf2} €/yr) — spouse in SK V", "Grundfreibetrag verdoppelt ({gbf2} €/Jahr) — Ehepartner in SK V", "Grundfreibetrag verdubbeld ({gbf2} €/jr) — partner in SK V", "Grundfreibetrag raddoppiato ({gbf2} €/anno) — coniuge in SK V", "Grundfreibetrag duplicado ({gbf2} €/año) — cónyuge en SK V",
        ],
        "DE_GBF_SK5" => [
            "No Grundfreibetrag — income fully taxable", "Kein Grundfreibetrag — Einkommen voll steuerpflichtig", "Geen Grundfreibetrag — inkomen volledig belastbaar", "Nessun Grundfreibetrag — reddito interamente imponibile", "Sin Grundfreibetrag — renta totalmente imponible",
        ],
        "DE_GBF_SK6" => [
            "No Grundfreibetrag + second-job surcharge", "Kein Grundfreibetrag + Zuschlag für Zweitjob", "Geen Grundfreibetrag + toeslag tweede baan", "Nessun Grundfreibetrag + maggiorazione secondo impiego", "Sin Grundfreibetrag + recargo por segundo empleo",
        ],
        "DE_SOLI_ANNEE_PRE" => [
            "In {an}, the full rate applied to everyone.", "Im Jahr {an} galt der volle Satz für alle.", "In {an} gold het volle tarief voor iedereen.", "Nel {an}, l'aliquota piena si applicava a tutti.", "En {an}, el tipo pleno se aplicaba a todos.",
        ],
        "DE_SOLI_ANNEE_POST" => [
            "In {an}, annual Lohnsteuer = {lst} € → Soli applicable.", "Im Jahr {an}, jährliche Lohnsteuer = {lst} € → Soli anwendbar.", "In {an}, jaarlijkse Lohnsteuer = {lst} € → Soli van toepassing.", "Nel {an}, Lohnsteuer annua = {lst} € → Soli applicabile.", "En {an}, Lohnsteuer anual = {lst} € → Soli aplicable.",
        ],
        _ => return None,
    };
    Some(row[i])
}
